AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless trigger-based application

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    LoggingConfig:
      LogFormat: JSON

Resources:
  MidasSaveDataSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "MidasSaveDataSQS.fifo"
      FifoQueue: true

  Subscriptions:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: arn:aws:sns:us-east-1:381492147695:MidasSendScraperDataSNS.fifo
      Endpoint: !GetAtt MidasSaveDataSQS.Arn

  MidasSaveDataSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MidasSaveDataSQS
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource: !GetAtt MidasSaveDataSQS.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: arn:aws:sns:us-east-1:381492147695:MidasSendScraperDataSNS.fifo

  MidasSaveDataLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      FunctionName: MidasSaveDataLambdaFunction
      Architectures:
      - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MidasSaveDataSQS.Arn



